#!/bin/bash

echo "Configuring alerta..."
cat <<EOF > ${OPENSHIFT_DATA_DIR}/alerta.conf
[DEFAULT]
timezone = Europe/London
log_dir = ${OPENSHIFT_PYTHON_LOG_DIR}
parser_dir = ${OPENSHIFT_DATA_DIR}
use_syslog = no

mongo_username = ${OPENSHIFT_MONGODB_DB_USERNAME}
mongo_password = ${OPENSHIFT_MONGODB_DB_PASSWORD}
mongo_database = ${OPENSHIFT_APP_NAME}
mongo_host = ${OPENSHIFT_MONGODB_DB_HOST}
mongo_port = ${OPENSHIFT_MONGODB_DB_PORT}

amqp_url = mongodb://${OPENSHIFT_MONGODB_DB_HOST}:${OPENSHIFT_MONGODB_DB_PORT}/${OPENSHIFT_APP_NAME}

EOF

export ALERTA_CONF=${OPENSHIFT_DATA_DIR}/alerta.conf
