#!/bin/bash

echo "Creating log directory ..."
mkdir /var/log/alerta

echo "Configuring alerta ..."
cat <<EOF > ${OPENSHIFT_DATA_DIR}/alerta.conf
[DEFAULT]
timezone = Europe/London
log_dir = ${OPENSHIFT_PYTHON_LOG_DIR}
parser_dir = ${OPENSHIFT_DATA_DIR}
use_syslog = no

mongo_username = ${OPENSHIFT_MONGODB_DB_USERNAME}
mongo_password = ${OPENSHIFT_MONGODB_DB_PASSWORD}
mongo_datatbase = ${OPENSHIFT_APP_NAME}
mongo_host = ${OPENSHIFT_MONGODB_DB_HOST}
mongo_port = ${OPENSHIFT_MONGODB_DB_PORT}

stomp_host = ${OPENSHIFT_PYTHON_IP}
stomp_port = 1500
inbound_queue: /queue/alerts

EOF

export ALERTA_CONF=${OPENSHIFT_DATA_DIR}/alerta.conf

echo "Installing STOMP message queue ..."
pip install python-daemon
pip install coilmq
coilmq -b ${OPENSHIFT_PYTHON_IP} -p 15000 -d
