#!/usr/bin/python

import os
import sys

sys.path.insert(0, os.path.dirname(__file__) or '.')
if os.path.exists(os.path.join(os.environ['OPENSHIFT_HOMEDIR'], "python-2.6")):
    PY_DIR = os.path.join(os.environ['OPENSHIFT_HOMEDIR'], "python-2.6")
else:
    PY_DIR = os.path.join(os.environ['OPENSHIFT_HOMEDIR'], "python")


virtenv = PY_DIR + '/virtenv/'

PY_CACHE = os.path.join(virtenv, 'lib', '2.6', 'site-packages')

os.environ['PYTHON_EGG_CACHE'] = os.path.join(PY_CACHE)
virtualenv = os.path.join(virtenv, 'bin/activate_this.py')

try:
    execfile(virtualenv, dict(__file__=virtualenv))
except IOError:
    pass

os.environ['ALERTA_CONF'] = os.path.join(os.environ['OPENSHIFT_DATA_DIR'], 'alerta.conf')

import _strptime

from alerta.app import app as application
